---
- name: ensure dependencies are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: latest
    force_apt_get: yes

- name: add redis apt key.
  apt_key:
    url: 'https://packages.redis.io/gpg'
    #id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: add redis repository
  apt_repository:
    repo: "{{ redis_apt_repository }}"
    state: present
    update_cache: true

- name: install redis
  package:
    name: redis
    state: latest

- name: disable default redis-server
  service:
    name: redis-server
    enabled: false
    state: stopped
