---
- import_tasks: check_vars.yml

- import_tasks: download.yml
  when: redis_install_from_source | d(false) | bool
  tags:
    - download

- import_tasks: dependencies.yml
  when: redis_install_from_source | d(false) | bool
  tags:
    - install

- import_tasks: install_from_source.yml
  when: redis_install_from_source | d(false) | bool
  tags:
    - install

- import_tasks: install_from_pkg.yml
  when: not redis_install_from_source | d(false) | bool
  tags:
  - install

- import_tasks: server.yml
  when: not redis_sentinel | bool
  tags:
    - config

- import_tasks: sentinel.yml
  when: redis_sentinel | bool
  tags:
    - config

- import_tasks: local_facts.yml
  when: redis_local_facts|bool

- import_tasks: haproxy.yml
  when: redis_haproxy_enabled | d(false) | bool
